### ISSUE TITLE
RuntimeError: masked_select: expected BoolTensor or ByteTensor for mask

### ISSUE THREAD

**Issue by zbbwss** [Tongjilibo/bert4torch#10]
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/bert_crf/train.py", line 191, in <module>
    model.fit(train_dataloader, epochs=20, steps_per_epoch=None, callbacks=[evaluator])
  File "D:\python36\lib\site-packages\bert4torch\models.py", line 213, in fit
    output, loss, loss_detail = self.train_step(train_X, train_y, grad_accumulation_steps)
  File "D:\python36\lib\site-packages\bert4torch\models.py", line 131, in train_step
    loss_detail = self.criterion(output, train_y)
  File "D:\python36\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:/Users/Administrator/Desktop/bert_crf/train.py", line 122, in forward
    return model.crf.neg_log_likelihood_loss(*outputs, labels)
  File "D:\python36\lib\site-packages\bert4torch\layers.py", line 913, in neg_log_likelihood_loss
    forward_score, scores = self._forward_alg(feats, mask)
  File "D:\python36\lib\site-packages\bert4torch\layers.py", line 862, in _forward_alg
    masked_cur_partition = cur_partition.masked_select(mask_idx)  # [x * tag_size]

**Comment by zbbwss** [comment]
版本是1.10 运行的平台windows10  pycharm

**Comment by zbbwss** [comment]
报错  RuntimeError: masked_select: expected BoolTensor or ByteTensor for mask

**Comment by zbbwss** [comment]
测试运行的脚本是ner任务：
/Tongjilibo/bert4torch/blob/master/examples/sequence_labeling/task_sequence_labeling_ner_crf.py

**Comment by zbbwss** [comment]
![image](https://user-images.githubusercontent.com/42829645/177266121-3fa5312b-4ecb-4dfd-8442-46bfafcbbfb6.png)

**Comment by zbbwss** [comment]
已经自我修复了  ，不知道是不是只有我自己的问题 还是说所有的都是这样的

**Comment by Tongjilibo** [comment]
> 已经自我修复了 ，不知道是不是只有我自己的问题 还是说所有的都是这样的

你是用的pip版本吗？pip上的0.1.6版本当时配合的task_sequence_labeling_ner_crf.py也是attention_mask转为bool类型的，后续我在CRF内部自己转bool()类型了，你可以用git上的最新代码试下，应该就没刚刚的问题了

**Comment by zbbwss** [comment]
是的用 pip install bert4torch 进行安装

**Comment by zbbwss** [comment]
直接git 是可以的  没有问题的

**Comment by zbbwss** [comment]
![image](https://user-images.githubusercontent.com/42829645/177290276-8a06b992-c8ef-4faf-9cf6-9f51223e0653.png)

**Comment by Tongjilibo** [comment]
> ![image](https://user-images.githubusercontent.com/42829645/177290276-8a06b992-c8ef-4faf-9cf6-9f51223e0653.png)

刚看到，你这边这个问题还有吗？
