### ISSUE TITLE
有关安装tensorrt python版遇到的问题

### ISSUE THREAD

**Issue by leizhu1989** [Tongjilibo/bert4torch#100]
大佬，你好，我在windows11下安装的tensorrt，在conda虚拟环境下安装的，可以import tensorrt，但是找不到common，import common，请问是怎们回事呢

**Comment by Tongjilibo** [comment]
我在markdown文档里面有给[百度云链接](https://pan.baidu.com/s/1vX3yK7BWQScnK_5Zb-pAkQ?pwd=rhq9)的

**Comment by leizhu1989** [comment]
嗯嗯，是我没仔细看。谢谢作者

**Comment by leizhu1989** [comment]
(nlp_sentence_0) D:\project\bert4torch>python examples/serving/task_simbert_tensorrt_python.py
Traceback (most recent call last):
  File "examples/serving/task_simbert_tensorrt_python.py", line 6, in <module>
    import tensorrt as trt
  File "C:\Users\zhulei\.conda\envs\nlp_sentence_0\lib\site-packages\tensorrt\__init__.py", line 129, in <module>
    ctypes.CDLL(find_lib(lib))
  File "C:\Users\zhulei\.conda\envs\nlp_sentence_0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] 找不到指定的程序。

大佬，这个看着像是tensorrt没装成功吗，我把tensorrt动态库lib加到了环境变量，python下import tensorrt也没问题

**Comment by Tongjilibo** [comment]
这个我还不太好确定，我之前使用window下的WSL来跑的

**Comment by leizhu1989** [comment]
嗯，在加载cublas64_11.dll报的错，说是找不到入口，这个库是在cuda目录下

**Comment by Tongjilibo** [comment]
#101
