### ISSUE TITLE
训练模型的时候在eval阶段就会oom

### ISSUE THREAD

**Issue by wjddd** [Tongjilibo/bert4torch#121]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: linux
- 你使用的**Python**版本: 3.10.9
- 你使用的**Pytorch**版本: 1.12.1
- 你使用的**bert4torch**版本: 0.2.7.post2
- 你加载的**预训练模型**: bert-base

### 核心代码
https://github.com/Tongjilibo/bert4torch/blob/master/examples/sentence_embedding/task_sentence_embedding_sup_CoSENT.py

### 输出信息
```shell
Evaluate:  80%|███████▉  | 3025/3799 [02:49<00:43, 17.88it/s]
Traceback (most recent call last):
  File "/home/train.py", line 185, in <module>
    model.fit(train_dataloader, epochs=3, steps_per_epoch=None, callbacks=[evaluator])
  File "/home/conda/envs/model_finetune/lib/python3.10/site-packages/torch4keras/model.py", line 278, in fit
    self.callbacks.on_epoch_end(self.global_step, self.epoch, logs)
  File "/home/conda/envs/model_finetune/lib/python3.10/site-packages/torch4keras/snippets.py", line 212, in on_epoch_end
    callback.on_epoch_end(global_step, epoch, logs)
  File "/home/model_finetune/train.py", line 158, in on_epoch_end
    val_consine = self.evaluate(valid_dataloader)
  File "/home/model_finetune/train.py", line 172, in evaluate
    embeddings = model.predict(batch_token_ids)
  File "/home/conda/envs/model_finetune/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/conda/envs/model_finetune/lib/python3.10/site-packages/torch4keras/model.py", line 294, in predict
    output = self._forward(train_X)
  File "/home/conda/envs/model_finetune/lib/python3.10/site-packages/torch4keras/model.py", line 89, in _forward
    return self.get_module().forward(train_X)
  File "/home/model_finetune/train.py", line 115, in forward
    hidden_state, pooler = self.bert([token_ids])
  File "/home/conda/envs/model_finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/conda/envs/model_finetune/lib/python3.10/site-packages/bert4torch/models.py", line 125, in forward
    outputs = self.apply_main_layers(outputs)
  File "/home/conda/envs/model_finetune/lib/python3.10/site-packages/bert4torch/models.py", line 490, in apply_main_layers
    hidden_states = grad_checkpoint(layer_module, *layer_inputs) if self.gradient_checkpoint else layer_module(*layer_inputs)
  File "/home/conda/envs/model_finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/conda/envs/model_finetune/lib/python3.10/site-packages/bert4torch/layers.py", line 531, in forward
    self_attn_output2 = self.feedForward(hidden_states)
  File "/home/conda/envs/model_finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/conda/envs/model_finetune/lib/python3.10/site-packages/bert4torch/layers.py", line 313, in forward
    x = self.intermediate_act_fn(self.intermediateDense(x))
RuntimeError: CUDA out of memory. Tried to allocate 48.00 MiB (GPU 0; 31.75 GiB total capacity; 27.43 GiB already allocated; 47.69 MiB free; 30.67 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### 自我尝试
显存为32G，已经尝试将 batch size 调为2，通过nvidia-smi查看只占2G显存，但eval阶段仍然会出现oom的情况

**Comment by Tongjilibo** [comment]
原来评估是结果取好了，concat在一起再计算指标，我修改成了在batch内计算cos距离，这样显存就小了，可以试试

**Comment by wjddd** [comment]
> 原来评估是结果取好了，concat在一起再计算指标，我修改成了在batch内计算cos距离，这样显存就小了，可以试试

感谢感谢，我去试试看
