### ISSUE TITLE
TypeError: forward() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by zhudongwork** [Tongjilibo/bert4torch#141]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: Ubuntu
- 你使用的**Python**版本: 3.8
- 你使用的**Pytorch**版本: 2.0.1+cu117
- 你使用的**bert4torch**版本: 
- 你加载的**预训练模型**: deberta

### 核心代码
```python
# 请在此处贴上你的核心代码
```

### 输出信息
```shell
# 请在此处贴上你的调试输出
```

### 自我尝试
使用最新的bert4torch遇到了这样的错误

Traceback (most recent call last):
  File "train.py", line 423, in <module>
    model.fit(train_dataloader, steps_per_epoch=None, epochs=epochs, callbacks=[evaluator])
  File "/usr/local/lib/python3.8/dist-packages/torch4keras/model.py", line 225, in fit
    self.output, self.loss, self.loss_detail = self.train_step(self.train_X, self.train_y)
  File "/usr/local/lib/python3.8/dist-packages/torch4keras/model.py", line 111, in train_step
    output = self._forward(train_X)
  File "/usr/local/lib/python3.8/dist-packages/torch4keras/model.py", line 94, in _forward
    return self.get_module().forward(*inputs, **input_kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given

**Comment by Tongjilibo** [comment]
应该是版本的问题，因为你用的example是最新的，但是torch4keras是老的，建议使用bert4torch==0.2.8和torch4keras==0.0.7.post3
