### ISSUE TITLE
Traceback (most recent call last):   File "task_sentiment_classification_hierarchical_position.py", line 117, in <module>     model.fit(train_dataloader, epochs=10, steps_per_epoch=None, callbacks=[evaluator])   File "/home/huangjiaheng/.local/lib/python3.8/site-packages/bert4torch/models.py", line 274, in fit     loss.backward(retain_graph=retain_graph)   File "/opt/conda/lib/python3.8/site-packages/torch/tensor.py", line 245, in backward     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)   File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward     Variable._execution_engine.run_backward( RuntimeError: cuda runtime error (710) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/THC/generic/THCTensorMath.cu:29

### ISSUE THREAD

**Issue by huangjiaheng** [Tongjilibo/bert4torch#24]

**Comment by Tongjilibo** [comment]
我这边是正常跑的，你是否是使用我给定的数据集跑的（这样可以确认是不是我代码的问题），如果是你用自己的数据集，请检查下修改的代码部分是否正确，看错误提示可能是下标越界的问题
