### ISSUE TITLE
对further pretrain的训练数据的格式要求？

### ISSUE THREAD

**Issue by XuJianzhi** [Tongjilibo/bert4torch#67]
https://github.com/Tongjilibo/bert4torch/tree/master/examples/pretrain/roberta_pretrain#L88
中对输入的训练数据的格式有什么要求？看了半天没看懂。。。
是对这些都行？[".bak", ".dat", ".dir", ".json"]

**Comment by Tongjilibo** [comment]
参考 #63

**Comment by XuJianzhi** [comment]
> 参考 #63

我越看越困惑。根据 #63 的回答，输入的训练文件是txt，一行一个样本。那也就是说 https://github.com/Tongjilibo/bert4torch/blob/master/examples/pretrain/roberta_pretrain/pretrain_roberta_mlm.py#L88 里的 cur_load_file 是该txt的路径。但：
1、 https://github.com/Tongjilibo/bert4torch/blob/master/examples/pretrain/roberta_pretrain/pretrain_roberta_mlm.py#L54 里默认是json文件；
2、即便把 MyDataset 的 _get_dataset_length 改成读取txt，https://github.com/Tongjilibo/bert4torch/blob/master/examples/pretrain/roberta_pretrain/pretrain_roberta_mlm.py#L59 的 load_data 也报错：
Traceback (most recent call last):
  File ".\pretrain_roberta_mlm_english.py", line 137, in <module>
    train_dataloader = get_train_dataloader()
  File ".\pretrain_roberta_mlm_english.py", line 133, in get_train_dataloader
    train_dataloader = DataLoader(MyDataset(train_data_path), batch_size=batch_size, shuffle=True, collate_fn=collate_fn)
  File ".\pretrain_roberta_mlm_english.py", line 79, in __init__
    self.db = self._load_data()
  File ".\pretrain_roberta_mlm_english.py", line 95, in _load_data
    return shelve.open(self.file)
  File "D:\S\Python37\lib\shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "D:\S\Python37\lib\shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "D:\S\Python37\lib\dbm\__init__.py", line 88, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determTraceback (most recent call last):
  File ".\pretrain_roberta_mlm_english.py", line 137, in <module>
    train_dataloader = get_train_dataloader()
  File ".\pretrain_roberta_mlm_english.py", line 133, in get_train_dataloader
    train_dataloader = DataLoader(MyDataset(train_data_path), batch_size=batch_size, shuffle=True, collate_fn=collate_fn)
  File ".\pretrain_roberta_mlm_english.py", line 79, in __init__
    self.db = self._load_data()
  File ".\pretrain_roberta_mlm_english.py", line 95, in _load_data
    return shelve.open(self.file)
  File "D:\S\Python37\lib\shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "D:\S\Python37\lib\shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "D:\S\Python37\lib\dbm\__init__.py", line 88, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined

感觉读取的还是一个json文件才对。

3、我没明白你在 #63 中说生成，是txt生成json吗？我看代码 https://github.com/Tongjilibo/bert4torch/blob/master/examples/pretrain/roberta_pretrain/pretrain_roberta_mlm.py#L86 只是 rename一下，并未把txt转为json。

**Comment by XuJianzhi** [comment]
明白了。
在运行data_gem.py时，报错：
https://github.com/Tongjilibo/bert4torch/blob/master/examples/pretrain/roberta_pretrain/pretrain_roberta_mlm_data_gen.py#L29
    self.token_pad_id = tokenizer._token_pad_id
AttributeError: 'Tokenizer' object has no attribute '_token_pad_id'
我看了 tokenizer 来源于 https://github.com/Tongjilibo/bert4torch/blob/master/examples/pretrain/roberta_pretrain/pretrain_roberta_mlm_data_gen.py#L189，
https://github.com/Tongjilibo/bert4torch/blob/master/bert4torch/tokenizers.py 里好像没有 _token_pad_id ？？

**Comment by Tongjilibo** [comment]
有点，逻辑在[tokenizer.py](https://github.com/Tongjilibo/bert4torch/blob/master/bert4torch/tokenizers.py#L246)
