### ISSUE TITLE
分类模型转onnx的时候报如下错误

### ISSUE THREAD

**Issue by wanglaiqi** [Tongjilibo/bert4torch#70]
Traceback (most recent call last):
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/torch/onnx/utils.py", line 750, in _export
    opened_file.write(proto)
AttributeError: 'bool' object has no attribute 'write'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "task_bert_cls_onnx.py", line 80, in <module>
    'output':{0: 'batch_size', 1: 'seq_len'}
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/torch/onnx/__init__.py", line 320, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/torch/onnx/utils.py", line 111, in export
    custom_opsets=custom_opsets, use_external_data_format=use_external_data_format)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/torch/onnx/utils.py", line 750, in _export
    opened_file.write(proto)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/torch/serialization.py", line 225, in __exit__
    self.file_like.flush()
AttributeError: 'bool' object has no attribute 'flush'

**Comment by Tongjilibo** [comment]
很难判断，首先先看下pytorch版本吧，我用的1.10
